### ISSUE TITLE
Error (16) no login-token found (wrong username or password).

### ISSUE THREAD

**Issue by miniluma** [frank-lie/DaikinCloud#2]
Hi,
since today afternoon, I get an error when requesting a tokenset.

"Error (16) no login-token found (wrong username or password)."

Onecta App works fine.
I also created a new account and added it to my home. Same error.

Any Idea?

**Comment by miniluma** [comment]
The response contains:


`{
  "callId": "...",
  "errorCode": 401020,
  "errorDetails": "Login Failed Captcha Required",
  "errorMessage": "Login Failed Captcha Required",
  "apiVersion": 2,
  "statusCode": 401,
  "statusReason": "Unauthorized",
  "time": "2024-03-23T19:43:13.351Z",
  "errorFlags": "captchaNeeded"
}`

**Comment by frank-lie** [comment]
Have you already run the module before or are you using it for the first time? If you used it the first time, make sure you are not using a social media login or gmail login. This doesn't work.

Furthermore the automatic login can fail, if the daikin website requires you to solve a captcha. That seems to be the problem here. However, I haven't had anything to do with this problem so far. But there ist workaround described [on this page](https://github.com/Apollon77/daikin-controller-cloud?tab=readme-ov-file#login-with-e-mailpassword)

I will release the revised module with the new Open API. At least there won't be this problem anymore.

**Comment by frank-lie** [comment]
Maybe it could also help to simply log out of the Onecta app and log in again. Other users had reported to me that this solved their problem. This was reported in the FHEM forum in this [post](https://forum.fhem.de/index.php?msg=1307555).

Currently, Daikin is making a new Open API available, but it is not yet completed. Daikin has announced that it wants to switch off the previous API. This is expected to happen in March/April 2024. Detailed information here in the [issue](https://github.com/rospogrigio/daikin_residential/issues/182). Thatsway there are currently failures with the old API.

**Comment by miniluma** [comment]
@frank-lie Thanks for your replies.

I'm using it since October, so I was surprised it suddenly stopped working.

After your replies, I played a bit with the accounts.
It's working now 🥳
But let me write down what I experienced:
1. The account I created yesterday was a Gmail account with a '+' in it. Maybe you know if you have name@gmail.com, name+something@gmail.com works as well.
I logged out and in again. Now, the response of the DaikinCloud module changed from captcha to forbidden. (I was wondering why, because I created this account yesterday and logged in and out several times yesterday to configure it.)
I was wondering if it was a permission thing in the app, so I gave this account owner permission. This hasn't changed the response.
2. I used the account I was using previously in the Module and logged in the app. Now, the app asked me something about my personal data, agreement of terms of usage (or something) and my language. 
The I retried to request the tokenset and it worked.

So it has an issue with the '+' maybe.

Thanks for your support! It helped to solve the issue.
